name: Manual Test-Run

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Run Script'
        default: './main.py'
        required: true

jobs:

  run:
  
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Fill credentials
      run: |
        rm ./config/credentials.json
        echo '${{ secrets.CREDENTIALS_JSON }}' > ./config/credentials.json && git checkout main
    
    - name: Run file
      run: python "${{ github.event.inputs.name }}"